name: "Docker Compose Health Check"
description: "Check health status of Docker Compose services"
inputs:
  max-retries:
    description: "Maximum number of retry attempts"
    required: false
    default: "30"
  retry-interval:
    description: "Interval between retries in seconds"
    required: false
    default: "10"
  compose-file:
    description: "Path to the docker-compose file"
    required: false
    default: "docker-compose.yml"
  skip-exited:
    description: "Skip checking exited containers"
    required: false
    default: "false"
  skip-no-healthcheck:
    description: "Skip checking containers without health checks"
    required: false
    default: "false"
runs:
  using: "composite"
  steps:
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20
    - name: Run the main job (health check)
      shell: bash
      env:
        INPUT_MAX_RETRIES: ${{ inputs.max-retries }}
        INPUT_RETRY_INTERVAL: ${{ inputs.retry-interval }}
        INPUT_COMPOSE_FILE: ${{ inputs.compose-file }}
        INPUT_SKIP_EXITED: ${{ inputs.skip-exited }}
        INPUT_SKIP_NO_HEALTHCHECK: ${{ inputs.skip-no-healthcheck }}
      run: node ${{ github.action_path }}/dist/index.js
