name: "Docker Compose Health Check"
description: "Check health status of Docker Compose services"
inputs:
  max-retries:
    description: "Maximum number of retry attempts"
    required: false
    default: "30"
  retry-interval:
    description: "Interval between retries in seconds"
    required: false
    default: "10"
  compose-file:
    description: "Path to the docker-compose file"
    required: false
    default: "docker-compose.yml"
  skip-exited:
    description: "Skip checking exited containers"
    required: false
    default: "false"
  skip-no-healthcheck:
    description: "Skip checking containers without health checks"
    required: false
    default: "false"
runs:
  using: "node20"
  main: "dist/index.js"
